/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdk_internal_misc_QBA */

#ifndef _Included_jdk_internal_misc_QBA
#define _Included_jdk_internal_misc_QBA
#ifdef __cplusplus
extern "C" {
#endif
#undef jdk_internal_misc_QBA_MAX_PARTITIONS
#define jdk_internal_misc_QBA_MAX_PARTITIONS 16384L
#undef jdk_internal_misc_QBA_MAX_SIDE_DATA
#define jdk_internal_misc_QBA_MAX_SIDE_DATA 64L
#undef jdk_internal_misc_QBA_STATS_SIZE
#define jdk_internal_misc_QBA_STATS_SIZE 64L
/*
 * Class:     jdk_internal_misc_QBA
 * Method:    registerNatives
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_QBA_registerNatives
  (JNIEnv *, jclass);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    version0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jdk_internal_misc_QBA_version0
  (JNIEnv *, jclass);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    versionString0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jdk_internal_misc_QBA_versionString0
  (JNIEnv *, jclass);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    create0
 * Signature: (JLjava/lang/String;ZIIIII)J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_QBA_create0
  (JNIEnv *, jclass, jlong, jstring, jboolean, jint, jint, jint, jint, jint);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    createSize0
 * Signature: (ZIIIII)J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_QBA_createSize0
  (JNIEnv *, jclass, jboolean, jint, jint, jint, jint, jint);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    destroy0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_QBA_destroy0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    getReference0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_QBA_getReference0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    setReference0
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_jdk_internal_misc_QBA_setReference0
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    allocate0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_QBA_allocate0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    deallocate0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_QBA_deallocate0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    reallocate0
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_QBA_reallocate0
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    clear0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_QBA_clear0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    size0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_QBA_size0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    base0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_QBA_base0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    sideData0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_QBA_sideData0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    next0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_QBA_next0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    stats0
 * Signature: (J[J[J)V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_QBA_stats0
  (JNIEnv *, jclass, jlong, jlongArray, jlongArray);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    allocateBulk0
 * Signature: (JJZ[J)I
 */
JNIEXPORT jint JNICALL Java_jdk_internal_misc_QBA_allocateBulk0
  (JNIEnv *, jclass, jlong, jlong, jboolean, jlongArray);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    deallocateBulk0
 * Signature: (J[J)V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_QBA_deallocateBulk0
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    allocateCount0
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_QBA_allocateCount0
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    deallocateCount0
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_QBA_deallocateCount0
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    allocateFit0
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_QBA_allocateFit0
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     jdk_internal_misc_QBA
 * Method:    deallocateFit0
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_QBA_deallocateFit0
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
